"""Vordefinierte Checklisten-Typen für die Pool-Pflege."""

from __future__ import annotations

CHECKLISTS: dict[str, dict] = {
    "weekly": {
        "label": "Wöchentliche Kontrolle",
        "icon": "📋",
        "description": "Regelmäßige Kontrolle für sauberes und sicheres Poolwasser.",
        "tasks": [
            {"key": "measure_water", "title": "Wassertest durchführen",
             "desc": "pH, freies Chlor, TA und CYA messen und dokumentieren."},
            {"key": "check_tablets", "title": "Chlortabletten kontrollieren",
             "desc": "Tabletten im Dosierer/Skimmer prüfen und ggf. nachfüllen."},
            {"key": "clean_skimmer", "title": "Skimmerkorb reinigen",
             "desc": "Laub und Grobschmutz aus dem Skimmerkorb entfernen."},
            {"key": "brush_walls", "title": "Wände und Boden abbürsten",
             "desc": "Ablagerungen abbürsten, damit Chlor und Filterung besser wirken."},
            {"key": "check_pump", "title": "Pumpe und Filter prüfen",
             "desc": "Pumpenlaufzeit und Filterdruck kontrollieren, ggf. Pumpenlaufzeit anpassen."},
            {"key": "check_water_level", "title": "Wasserstand kontrollieren",
             "desc": "Wasserstand auf Normalhöhe (Skimmermitte) halten."},
        ],
    },
    "spring": {
        "label": "Saisoneröffnung",
        "icon": "🌱",
        "description": "Pool nach der Winterpause fit machen für die neue Saison.",
        "tasks": [
            {"key": "remove_cover", "title": "Poolabdeckung entfernen",
             "desc": "Abdeckplane reinigen, trocknen und trocken einlagern."},
            {"key": "clean_pool", "title": "Pool gründlich reinigen",
             "desc": "Wände und Boden schrubben, Schmutzwasser absaugen oder ablassen."},
            {"key": "fill_water", "title": "Wasser auffüllen",
             "desc": "Wasserstand auf Normalhöhe (Skimmermitte) bringen."},
            {"key": "clean_filter", "title": "Filter rückspülen / reinigen",
             "desc": "Sandfilter rückspülen oder Filtereinsatz reinigen/ersetzen."},
            {"key": "check_equipment", "title": "Technik prüfen",
             "desc": "Pumpe, Filter, Heizung und Zubehör auf Funktion testen."},
            {"key": "first_measurement", "title": "Erstmessung durchführen",
             "desc": "pH, Chlor, TA und CYA messen und dokumentieren."},
            {"key": "adjust_ta", "title": "TA (Alkalinität) einstellen",
             "desc": "TA auf Zielwert bringen (zuerst, da sie den pH stabilisiert)."},
            {"key": "adjust_ph", "title": "pH-Wert einstellen",
             "desc": "pH auf Zielwert (7,2–7,4) bringen."},
            {"key": "shock_chlorination", "title": "Stoßchlorung durchführen",
             "desc": "Pool durchchloren (Ziel ≥ 10 mg/l freies Chlor), dann warten bis < 3 mg/l."},
            {"key": "refill_tablets", "title": "Langsamlöser-Tabs einlegen",
             "desc": "Dosierer / Schwimmdosierer mit Chlortabletten befüllen."},
        ],
    },
    "winter": {
        "label": "Winterisierung",
        "icon": "❄️",
        "description": "Pool sicher durch die Winterpause bringen.",
        "tasks": [
            {"key": "last_measurement", "title": "Abschlussmessung",
             "desc": "Alle Werte messen und dokumentieren."},
            {"key": "shock_before_winter", "title": "Stoßchlorung",
             "desc": "Pool vor der Pause durchchloren, damit Keime und Algen keine Chance haben."},
            {"key": "lower_water", "title": "Wasserstand absenken",
             "desc": "Wasser unter Skimmer und Einlassdüsen ablassen (Frostschutz)."},
            {"key": "drain_pipes", "title": "Leitungen entleeren / frostsicher machen",
             "desc": "Filter, Pumpe und alle Leitungen entleeren oder mit Frostschutzmittel befüllen."},
            {"key": "remove_accessories", "title": "Zubehör einlagern",
             "desc": "Leiter, Thermometer, Reinigungsgeräte, Spielzeug – alles trocken einlagern."},
            {"key": "algaecide_winter", "title": "Winter-Algizid zugeben",
             "desc": "Spezielles Winteralgizid für die Ruhephase zugeben."},
            {"key": "close_filter", "title": "Filter und Pumpe sichern",
             "desc": "Pumpe entleeren, Multiport-Ventil auf 'Winter' stellen."},
            {"key": "cover_pool", "title": "Pool abdecken",
             "desc": "Winterabdeckung befestigen und sichern, Spannung gleichmäßig verteilen."},
        ],
    },
}
